<?php
/*
function setComment(){
  if (isset($_POST['postSubmit'])) {
    $body = $_POST['body'];
    $id = $_POST['id'];
    $date = $_POST['date'];
    $body= $_POST['comment'];
    $title = $_POST['title'];

    $sql = "INSERT INTO threads (title, owner_id, owner_name, date, title) VALUES ('$username', '$date', '$title' )";

  }
}
*/
/*
function getPostNumber($conn){
  //include_once 'includes/dbh-inc.php';
  $sql = "SELECT * FROM posts ORDER BY id DESC LIMIT 1";
  $result = mysqli_query($conn, $sql);
  $row = mysqli_fetch_assoc($result);
  return $row['id'] + 1;;
}
*/
function setReply($threadid){
  if (isset($_POST['postSubmit'])) {
    include_once 'dbh-inc.php';
    include_once 'createthread-inc.php';

    // variables from the newthread page
    $username = $_POST['username'];
    $body = strip_tags($_POST['comment']);
    $id = $_POST['id'];
    $posts = json_encode (array (1 => getPostNumber($conn)));

/*
    // insert some data into the "threads" DB first
    $sql = "INSERT INTO threads (title, owner_id, owner_name, posts) VALUES ('$title', '$id', '$username', '$posts')";
    $result = mysqli_query($conn, $sql);

    if (!$result) { // error check
      echo "Error: " . $sql . "<br>" . mysqli_error($conn);
    }
*/
/*
    // gets the id of the thread we just made from the DB because it's a primary
    // key auto generated by the db
    $sql = "SELECT posts FROM threads WHERE id='$id'";
    $result = mysqli_query($conn, $sql);
    $row = mysqli_fetch_assoc($result);
    */
    // then the rest of the data, like the body of the post, goes into the posts
    // DB. since threads are just arrarys of post IDs things are seperated.
    $sql = "INSERT INTO Posts (Body, OwnerID, Username, ThreadID) VALUES ('$body', '$id', '$username', '$threadid')";
    $result = mysqli_query($conn, $sql);

    if (!$result) { // error check
      echo "Error: " . $sql . "<br>" . mysqli_error($conn);
    }

    header('Location: ../blerkingblitle/viewthread.php?threadid='.$threadid.'');
    exit();

  }
}
