<?php
include_once('safeEscape-inc.php');

function getPostNumber($conn){
  //include_once 'includes/dbh-inc.php';
  $sql = "SELECT * FROM Posts ORDER BY ID DESC LIMIT 1";
  $result = mysqli_query($conn, $sql);
  $row = mysqli_fetch_assoc($result);
  return $row['id'] + 1;
}


// if (isset($_POST['threadSubmit']) == true and $_POST['title'] == true and $_POST['body'] == true) {
if (isset($_POST['threadSubmit']) ) {
  if ($_POST['title'] == true or $_POST['comment'] == true){
    header('Location: newthread.php?error=threaderror');
  }

  include_once 'dbh-inc.php';

  // variables from the newthread page
  $username = $_POST['username'];
  $id = $_POST['id'];
  //  $date = $_POST['date']; // getting the data clientside??? DUURRRRR
  $date = date('Y-m-d H:i:s'); // much better
  $body = escapeBody($conn, $_POST['comment']);
  // $body = mysqli_real_escape_string($conn, str_replace('\r\n', '', nl2br(htmlspecialchars(strip_tags($_POST['comment'])))));
  // $body= mysqli_real_escape_string($conn, strip_tags($_POST['comment']));
  // $title = mysqli_real_escape_string($conn, str_replace('\r\n', '', nl2br(htmlspecialchars($_POST['title']))));
  $title = escapeBody($conn, $_POST['title']);
  $posts = json_encode (array (1 => getPostNumber($conn)));

  // insert some data into the "threads" DB first
  $sql = "INSERT INTO threads (Title, OwnerID, Username, Posts) VALUES ('$title', '$id', '$username', '$posts')";
  $result = mysqli_query($conn, $sql);

  if (!$result) { // error check
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
  }

  // gets the id of the thread we just made from the DB because it's a primary
  // key auto generated by the db
  $sql = "SELECT ID FROM Threads WHERE Title='$title'";
  $result = mysqli_query($conn, $sql);
  $row = mysqli_fetch_assoc($result); // thread ID, not the user ID

  // then the rest of the data, like the body of the post, goes into the posts
  // DB. since threads are just arrarys of post IDs things are seperated.
  $sql = "INSERT INTO Posts (Body, OwnerID, Username, ThreadID) VALUES ('$body', '$id', '$username', '$row[ID]')";
  $result = mysqli_query($conn, $sql);

  if (!$result) { // error check
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
  }

  // FIX THIS!!!!
  header('Location: ../viewthread.php?threadid='.$row["ID"]);
  exit();

}
